### ISSUE TITLE
Battery Capacity doesnt seem to be returning correctly

### ISSUE THREAD

**Issue by ecam315** [MaffooClock/SerialRenogy#3]
battery shows 100% even when on battery overnight,  Based on calculations, it should be dropping to something around 95% by morning.

**Comment by MaffooClock** [comment]
Care to share what hardware you're using?

I haven't observed this problem with my Rover nor Wanderer.  If there's something wrong with the data, I would be inclined to think it's the controller, not this utility -- all this utility does is read various registers to retrieve the data (with minimal processing for data that needs it).

Battery capacity, in particular, is [read straight from the register](https://github.com/MaffooClock/SerialRenogy/blob/7c8007afbb0b3ff4b35a2ba0777d34cf34f18fa6/renogy.js#L215-L216) without any processing.

Here's a screenshot from Grafana of battery capacity from my [Renogy Rover 20A](https://www.renogy.com/rover-li-20-amp-mppt-solar-charge-controller/) for the past 7 days, just to prove my sanity:
![screenshot from Grafana showing battery capacity over past 7 days](https://github.com/user-attachments/assets/7f1adad0-4db8-4883-82eb-2b9b25796f4f)

I guess it's possible Renogy might have changed the firmware in more recent models to have different register addresses, in which case this utility would then be trying to read the wrong data.

You could view `http://<host>:<port>/info.json` to see the model and hardware/software versions.

**Comment by ecam315** [comment]
{"controllerV":24,"controllerC":20,"controllerDischgC":20,"controllerType":"Controller","controllerModel":"RNG-CTRL-RVR20","softwareVersion":"V4.1.1","hardwareVersion":"V0.0.6","serialNumber":1444147,"controllerAddress":1}

It is a Rover Li 20 amp.

I just looked back over the last 7 days, and it did actually drop down to 97% after a day of low production.

![image](https://github.com/user-attachments/assets/026badb6-eabf-4616-b6a2-829690c893c8)

So, maybe false report on my end, I shut the panel off today for testing.
